# Generated by Django 5.2.2 on 2025-06-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('avg_wpm', models.FloatField(blank=True, default=0.0, null=True)),
                ('last_wpm', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
